project:
  type: website
  output-dir: docs

website:
  title: "Ollie Website"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: slate
    css: styles.css



